-- PRS Episode Command Center — Rob Morrow RE-seed
-- Paste-and-run helper for Supabase to update Jeremy's existing rows to the new self-contained instructions.
-- Safe to run multiple times — the delete clears all existing Rob Morrow checklist rows first, then the inserts recreate them from scratch.
-- Does NOT touch prs_episodes (the episode row is preserved with its toggled/non-toggled state intact).

begin;

-- 1) Clear existing Rob Morrow checklist items.
delete from prs_checklist_items
where episode_id = (select id from prs_episodes where slug = 'rob-morrow');

-- 2) Reinsert with the new self-contained instructions_md bodies.
with ep as (select id from prs_episodes where slug = 'rob-morrow')
insert into prs_checklist_items (episode_id, role_group, title, instructions_md, sort_order)
select ep.id, x.role_group, x.title, x.instructions_md, x.sort_order
from ep, (values
  -- Editorial (pre-edit) -------------------------------------------------
  ('Editorial', 'Apply 🔴 compliance trim: father-suicide method (~40:00)', E'Tyler describes his father''s death by suicide and states the method ("shot himself in the head"). YouTube''s suicide-policy classifier targets method language specifically.\n\n**Fix:** trim to "my father took his own life" OR "my father died by suicide". Keeps the entire narrative weight (second grade, abusive stepfather follow-on, "I was a difficult kid") — drops only the method phrase.\n\nThis is the highest-leverage compliance edit in the episode. Sam Miller / Blake-era learning: the auto-classifier is aggressive on suicide-method language.', 10),
  ('Editorial', 'Confirm sponsor reads intact', E'Three sponsor placements to verify in the line cut:\n\n• **BetterHelp** at ~29:03 → 30:13 — formal mid-roll. Tyler delivers personally; includes the BetterHelp.com/punkrock discount code.\n• **Morning Watcher** at ~1:17:40 — organic. Tyler hands Rob a sample on-mic.\n• **Boom Boom Stick** at ~1:18:49 — organic. Tyler self-IDs it: "my other sponsor is this thing called Boom Boom Stick."\n\n**Hard rule:** no host-read ad within 60 seconds of the weed-edible / child-hospitalization story (~43:00). BetterHelp at 29:00 is fine; verify nothing got moved.', 20),
  ('Editorial', 'Editorial call: #MeToo segment (~51-56 min)', E'Tyler calls James Franco "railroaded" ("Railroaded. Railroaded.") and is dismissive of the Al Franken story ("all he did was go honk, honk… I don''t think he actually honked her boobs"). Rob is more measured: "the correction of certain behavior has to be addressed… my guess is he did something."\n\n**Single most backlash-prone segment in the episode.** Not a platform-suppression risk; a reputational one. Tyler''s stance is more provocative than Rob''s.\n\n**Three options:**\n1. Keep verbatim.\n2. Soften Tyler''s lines.\n3. Cut the segment and bridge to the next beat (Armie Hammer, ~56:40).\n\nFlagged so it does not ship by accident.', 30),
  ('Editorial', 'Lock the edit', E'Pass the locked cut to post-edit cleanup (intro audit + chapter timestamp verification + ad-spot 60-sec buffer re-check).\n\nAlso consider: tighten Tyler''s ~10-min optimization middle (~13:30-23:30, Adderall/peptides/ozempic/testosterone) so Rob stays the focus. Editorial call, not compliance — same recommendation we made on Blake and Josh.', 40),

  -- Metadata & Upload ----------------------------------------------------
  ('Metadata & Upload', 'Set YouTube title', E'**Recommended (Variant A, 64 char):**\nNorthern Exposure''s Rob Morrow on Treating Anger Like an Addiction\n\n**Why A:** "Northern Exposure" front-loaded (live search term, Amazon Prime resurgence) + "Rob Morrow" (guest) + the distinctive "anger like an addiction" hook in one line — three SEO anchors in 64 characters.\n\n**Alternates Tyler can pick from:**\n• **B (56 char, quote-driven):** Rob Morrow: "Drugs Keep You From the Thing You''re Chasing"\n• **C (60 char, recognition + scope):** Rob Morrow on Northern Exposure, Pot, Anger & 40 Years of Art\n• **D (51 char, curiosity/myth-correction):** Rob Morrow on Why He Really Left Northern Exposure\n• **E (49 char, process-addiction angle):** Rob Morrow: The Addiction Recovery No One Expects\n\n💡 The §8 banned-word filter applies to **paid ad headlines, descriptions, and thumbnail text only** — NOT to the YouTube title or description. "Addiction" / "Recovery" / "Sober" / "Drugs" can all appear in the title.', 50),
  ('Metadata & Upload', 'Set description + 10 hashtags + 28 tags', E'**Description (paste verbatim):**\n\nNorthern Exposure''s **Rob Morrow** joins Tyler Ramsey on the Punk Rock Sober Podcast for a conversation between two working artists about recovery, craft, and the long game.\n\nRob opens up about a recovery most people never hear framed as recovery — from anger and marijuana — why he says "anger is a drug," and the line that reframes addiction entirely: drugs keep you from the very thing you''re taking them to get.\n\n**In this episode:**\n· Why anger is an addiction — and how Rob recovered from it\n· The real reason he left Northern Exposure at its peak (it wasn''t money)\n· "Drugs keep you from having the thing you''re taking the drugs to have"\n· The "stoner draft" — and the true cost of creating high\n· Co-founding the Naked Angels theater company with Marisa Tomei, Sarah Jessica Parker & Matthew Broderick\n· His first movie — co-starring a 21-year-old Johnny Depp in the worst film ever made\n· The 900-page memoir novelist Don Winslow championed\n· "Live your life backward and everything makes sense"\n· The Noah Wyle mantra Rob says every day\n· *Death of a Salesman* — the high point of a 40-year career\n\n---\n\n🔗 Guest: Rob Morrow · *Northern Exposure* · *Numb3rs* · *The People v. O.J. Simpson* · *Northern Disclosure* podcast (with Janine Turner)\n🎙️ Host: Tyler Ramsey · Punk Rock Sober\n\nIf you or someone you love is struggling: 988 (Suicide & Crisis Lifeline, US) · SAMHSA 1-800-662-4357 (24/7, free).\n\n#RobMorrow #NorthernExposure #PunkRockSober #Numb3rs #AngerIsADrug #Recovery #TheArtistsLife #90sTV #SoberArtist #ProcessAddiction\n\n---\n\n**Hashtags (10, paste in description):**\n`#RobMorrow` `#NorthernExposure` `#PunkRockSober` `#Numb3rs` `#AngerIsADrug` `#Recovery` `#TheArtistsLife` `#90sTV` `#SoberArtist` `#ProcessAddiction`\n\n**Tags (28, comma-separated, paste-ready into YouTube tags field):**\n\n```\nrob morrow, rob morrow interview, rob morrow podcast, rob morrow northern exposure, northern exposure, northern exposure cast, northern exposure cast now, rob morrow numb3rs, numb3rs cast, rob morrow numbers, rob morrow now, rob morrow memoir, northern disclosure podcast, janine turner, rob morrow people v oj simpson, barry scheck actor, rob morrow actor, anger management podcast, anger addiction, process addiction, recovery podcast, marijuana recovery, weed sobriety, punk rock sober, tyler ramsey, sober actor, 90s tv shows interview, naked angels theater company, johnny depp private resort, working artist podcast\n```\n\nNote: includes both "Numb3rs" (digit-three) and "Numbers" (text) for searchability.', 60),
  ('Metadata & Upload', 'Add 36 chapter markers', E'Paste verbatim into YouTube''s chapter field (in the video description). First chapter is 0:00 (required); all 36 are ≥ 10 sec apart.\n\n```\n0:00 — Cold open: "Anger is a drug"\n0:30 — Curiosity as the new drug (Tyler''s intro)\n1:50 — Why Northern Exposure refuses to age (the Amazon Prime resurgence)\n3:00 — The real reason he left at the peak — and the money myth\n6:30 — Two road dogs in the secret recovery group\n9:40 — "What are you recovering from?" — pot and anger\n10:30 — Anger as a drug, and the seduction of righteous anger\n11:00 — The Clockwork Orange effect\n12:15 — All my heroes used anger as power\n13:30 — Tyler''s Adderall years and the "art monster"\n15:45 — The stoner draft — creating high\n17:15 — Stand-up comedy at 50, and the temptation to numb\n18:00 — Peptides, the Wolverine shot & the longevity rabbit hole\n22:00 — Testosterone, energy & the price of optimization\n23:40 — Rob the multi-disciplinary artist — and the novel\n27:00 — Why screenplays aren''t art, but novels are\n29:00 — BetterHelp\n30:14 — The 900-page memoir Don Winslow couldn''t put down\n36:40 — The best memoirs: Josh Brolin, Lena Dunham\n38:00 — The night "Punk Rock Sober" finally clicked\n40:00 — Tyler''s childhood — and learning to forgive yourself\n43:00 — The weed-edible night that scared him sober\n45:30 — His first movie, with a 21-year-old Johnny Depp\n49:00 — Co-founding the Naked Angels with the It-crowd of New York\n51:00 — Forgiveness, James Franco & the #MeToo correction\n56:40 — Armie Hammer, and what real comebacks cost\n58:00 — Charlie Sheen''s private plane (it wasn''t insulin)\n59:50 — JFK Jr. on the Naked Angels board\n1:05:00 — The Dennis Hopper moment that said "you''re on the right path"\n1:07:00 — John Travolta: the catalyst, then the full circle\n1:09:00 — Live your life backward and it all makes sense\n1:12:25 — Drugs keep you from the thing you''re chasing\n1:15:00 — The Noah Wyle mantra Rob says every day\n1:16:00 — Death of a Salesman — the high point of a 40-year career\n1:19:50 — Art as a way to love yourself\n```', 70),
  ('Metadata & Upload', 'Upload thumbnail', E'**Recommended: Concept A — "ANGER IS A POISON"** (predicted A/B winner: HIGH)\n\n⚠️ Do NOT use "ANGER IS A DRUG" — "DRUG" is a §8 banned token and thumbnail text is the strongest Health-classifier trigger we have (Sam Miller "ROCK BOTTOM" → "Prescription Opioid Painkillers" precedent). Classifier matches tokens, not meaning. **"POISON"** is Rob''s own language at ~13:52 ("Whenever I would get really raged, it felt like poison") and is fully clean.\n\n**Format (two-face podcast layout):**\n• Rob Morrow LEFT, Tyler RIGHT — both head-and-shoulders, equal size, same vertical position.\n• Dark high-contrast charcoal background with subtle radial gradient.\n• Central text: "**NORTHERN EXPOSURE''S**" white (smaller top line) · "**ROB MORROW**" oversized white below · "**ANGER IS A POISON**" stacked below in bold red.\n• Small "NEW" badge top-left in red.\n\n**Alternate concepts:**\n• **Concept B (MED-HIGH)** — Quote hook. Text: "**WHAT YOU''RE CHASING**" white / "**IS WHY YOU CAN''T REACH IT**" red. (Do NOT use "DRUGS KEEP YOU FROM" — §8 trip on "DRUGS".) Dark navy background.\n• **Concept C (MED)** — Curiosity/Recognition. Text: "**WHY HE LEFT**" white / "**AT THE PEAK**" bold yellow. Deep black background. Rob slight wry smile, Tyler intrigued.\n\nThumbnail-text literal §8 check: all three concepts pass. "ANGER IS A POISON," "WHAT YOU''RE CHASING," "IS WHY YOU CAN''T REACH IT," "WHY HE LEFT," "AT THE PEAK" — all clean.', 80),
  ('Metadata & Upload', 'Upload video as scheduled YouTube Premiere', E'Confirm date + time.\n\n**Critical note:** a YouTube Premiere cannot be advertised on Google Ads until after it airs (Google Ads rejects an unaired premiere as an ad asset; learned on Blake — strategy v1.2.1 §12). Build the ad campaign now and leave PAUSED; launch within ~15 min of premiere ending.', 90),

  -- Ads & Marketing ------------------------------------------------------
  ('Ads & Marketing', 'Build Custom Segment (20 keywords)', E'**Path:** Tools & Settings → Audience Manager → Custom segments → "+ New custom segment" → "People who searched for any of these terms on Google"\n\n**Segment name:** `Rob Morrow / Northern Exposure`\n\n**20 keywords (paste-ready, one per line):**\n\n```\nrob morrow\nrob morrow interview\nrob morrow podcast\nrob morrow northern exposure\nnorthern exposure\nnorthern exposure cast\nnorthern exposure cast now\nrob morrow numb3rs\nnumb3rs cast\nrob morrow numbers\nrob morrow now\nrob morrow memoir\nnorthern disclosure podcast\njanine turner\nrob morrow actor\nrob morrow people v oj simpson\n90s tv cast interview\nclassic tv actors podcast\nanger management podcast\npunk rock sober\n```', 100),
  ('Ads & Marketing', 'Set audience + geo + budget', E'**Audience build (Audience Manager → Audiences → "+ New audience"):**\n• Audience name: `Rob Morrow / Northern Exposure`\n• Custom segments (include): the segment from previous step\n• **Exclusions:** `All Channel Viewers` (don''t re-serve existing viewers)\n• Demographics: All (default; 25-65 inherits at campaign level)\n\n**Ad group build (Campaign `PRS — New Episode Launch` → Ad groups → "+ Ad group"):**\n• Ad group name: `Rob Morrow — Launch`\n• Attach the Audience above\n• Content targeting (keywords/topics/placements): leave EMPTY\n• Audience expansion: **OFF**\n• Format: Skippable in-stream\n• Bid: Target CPV $0.05\n\n**Campaign-level settings to verify:**\n• Daily budget: **$80/day**\n• Locations: **United States only** (per Strategy v1.2.1 — sponsor optics; all future ad groups default US-only)\n• Campaign end date: **activation_date + 5 days** (auto-pauses on day 6 — total 5 × $80 = **$400**)\n• Bid strategy: Target CPV $0.05\n• Audience expansion: OFF', 110),
  ('Ads & Marketing', 'Build ad copy (banned-word verified)', E'Every line below verified clean against the §8 banned-word list (depression, depressed, mental health, suicide, suicidal, trauma, PTSD, anxiety, OCD, bipolar, addict, addiction, sober, sobriety, recovery, rehab, relapse, drug, drugs, pot, marijuana, weed, pills, self-harm, dark place, rock bottom, hit bottom, walked away, killed, saved). Also avoids the "Walked Away" #WalkAway meme and the "What He Was Really…" curiosity-gap pattern that tripped Clickbait on Josh Peck''s Ad 2.\n\n**8 long headlines (≤90 char):**\n1. Northern Exposure''s Rob Morrow — The Full Conversation (54)\n2. Rob Morrow On Anger, Art, and 40 Years in Hollywood (51)\n3. Rob Morrow: Why He Left Northern Exposure At Its Peak (52)\n4. Northern Exposure''s Rob Morrow On What Anger Cost Him (52)\n5. Rob Morrow On The Thing That Did The Most Damage (48)\n6. Rob Morrow: 40 Years An Artist — The Honest Version (51)\n7. Northern Exposure''s Rob Morrow Opens Up — Full Episode (54)\n8. Rob Morrow On Anger, Art & The Long Game (40)\n\n**7 short headlines (≤30 char):**\n1. Northern Exposure: Rob Morrow\n2. Rob Morrow On Anger & Art\n3. Why He Left At The Peak\n4. What Anger Cost Him\n5. Rob Morrow: 40 Years In\n6. Rob Morrow Opens Up\n7. The Most Damage\n\n**3 descriptions (≤90 char):**\nA. Northern Exposure''s Rob Morrow on anger, art, and 40 years in Hollywood. (71)\nB. The full conversation with Rob Morrow — Northern Exposure, craft, and the long game. (84)\nC. A different side of Rob Morrow — reflective, funny, and 40 years deep. (69)\n\n⚠️ Do NOT use the in-conversation phrase "DRUGS KEEP YOU FROM" in any overlay or copy — superseded by "WHAT YOU''RE CHASING / IS WHY YOU CAN''T REACH IT" for Concept B.', 120),
  ('Ads & Marketing', 'Set display URL (two-box field)', E'**Path 1:** `Painful-Lessons`\n**Path 2:** `Rob-Morrow`\n\nRenders on ad creative as `youtube.com/Painful-Lessons/Rob-Morrow`. One channel ("Punk Rock Sober"). "Painful Lessons" is a display-label convention on ad creative only, not a separate channel. (Strategy §8.)', 130),
  ('Ads & Marketing', 'Build campaign and leave PAUSED', E'Have everything ready (custom segment, audience, ad copy, display URL, two ads) but **pause the campaign** until the premiere finishes airing.\n\n**Ad 1 (Recognition Play — mirrors thumbnail Concept A):**\n• Long headline: `Northern Exposure''s Rob Morrow — The Full Conversation`\n• Short headline: `Rob Morrow On Anger & Art`\n• Description: `Northern Exposure''s Rob Morrow on anger, art, and 40 years in Hollywood.`\n• CTA: `Watch`\n• Display URL: `Painful-Lessons` / `Rob-Morrow`\n\n**Ad 2 (Curiosity / Recognition — mirrors thumbnail Concept C):**\n• Long headline: `Rob Morrow: Why He Left Northern Exposure At Its Peak`\n• Short headline: `Why He Left At The Peak`\n• Description: `The full conversation with Rob Morrow — Northern Exposure, craft, and the long game.`\n• CTA: `Watch`\n• Display URL: `Painful-Lessons` / `Rob-Morrow`\n\nBoth headlines are declarative — avoids the "What He Was Really…" / "Why He Really…" curiosity-gap pattern that tripped Clickbait on Josh Peck''s Ad 2. Neither uses "Walked Away" wording ("Left" is the §8-approved replacement).', 140),
  ('Ads & Marketing', '⭐ Launch the Google Ads campaign right after premiere ends', E'Within ~15 min of the premiere finishing, build the ad group on the now-public video and launch.\n\n**This is the step a recent episode missed — do not let this ship unchecked.**\n\nFinal URL on both ads = the full episode (not a teaser clip). Set campaign end date to activation_date + 5 days. Confirm Locations = United States only. Activate → 5 days × $80/day = $400.\n\nAlso: update `Retarget — Newest Episode` ad group in `PRS — Retargeting Flywheel` to point at Rob''s URL.', 150),

  -- Social & Clips -------------------------------------------------------
  ('Social & Clips', 'Produce the 6 social clips', E'Six clip candidates, 30-90 sec each. Schedule across launch week.\n\n**Clip 1 — "Anger is a drug" · the spine**\n• Timestamp: ~00:09:43 → ~00:10:30 (~45 sec)\n• Hook (first 3 sec): "What are you recovering from?" — Rob: "Well, my main thing was pot. Anger and pot."\n• Caption: Rob Morrow on the recovery no one calls recovery.\n• On-screen text: "ANGER IS A DRUG."\n• Platforms: all (organic)\n• Compliance: ⚠️ "marijuana," "pot," and "drug" all in opener. Fine for organic socials. **Do NOT use as paid ad creative** — §8 trigger.\n\n**Clip 2 — "Drugs keep you from the thing you''re chasing" · BEST PAID**\n• Timestamp: ~01:12:25 → ~01:12:44 (~19 sec)\n• Hook (first 3 sec): "It''s funny how drugs keep you from having the thing you''re taking the drugs to have."\n• Caption: The 14 words that reframe addiction completely.\n• On-screen text: "WHAT YOU''RE CHASING IS WHY YOU CAN''T REACH IT." (avoids the literal "DRUGS" token in overlay for paid reuse — the audio still contains it but overlays are what the thumbnail classifier reads)\n• Platforms: all — best paid-ad-creative candidate when the overlay is the version above.\n• Compliance: ✅ overlay text clean.\n\n**Clip 3 — "All my heroes used anger as power"**\n• Timestamp: ~00:12:16 → ~00:13:34 (~70 sec, trim hard)\n• Hook: "My sense of anger as a young person was that it was power."\n• Caption: Rob Morrow on where men learn that anger equals strength.\n• On-screen text: "ANGER AS POWER."\n• Platforms: TikTok / Reels / X — male-skew audience\n• Compliance: ✅ Clean.\n\n**Clip 4 — Why he left Northern Exposure**\n• Timestamp: ~00:03:10 → ~00:04:00 (~50 sec)\n• Hook: "People think I left because I wanted more money. That wasn''t the case."\n• Caption: Rob Morrow corrects the 30-year-old story on leaving Northern Exposure.\n• On-screen text: "IT WASN''T ABOUT THE MONEY."\n• Platforms: all — Northern Exposure nostalgia communities pull hardest here.\n• Compliance: ✅ Clean. Best Recognition-play clip.\n\n**Clip 5 — Johnny Depp & Private Resort**\n• Timestamp: ~00:46:01 → ~00:48:48 (trim to ~70 sec)\n• Hook: "My first movie was with Johnny Depp. We were 21 and 22."\n• Caption: Rob Morrow on co-starring with a 21-year-old Johnny Depp in the worst movie ever made.\n• On-screen text: "BEFORE JOHNNY DEPP WAS JOHNNY DEPP."\n• Platforms: all — recognition-heavy, fun, low-stakes\n• Compliance: 🟢 Clean.\n\n**Clip 6 — "Live your life backward"**\n• Timestamp: ~01:09:00 → ~01:10:00 (~55 sec)\n• Hook: "If you live your life backward, everything makes sense."\n• Caption: Rob Morrow on reading the signs along the path.\n• On-screen text: "LIVE YOUR LIFE BACKWARD."\n• Platforms: all — self-help / personal-growth crossover\n• Compliance: ✅ Clean.\n\nClip 2 (with the overlay alternate) is the best paid-ad-creative candidate.', 160),
  ('Social & Clips', 'Produce the 3 collab clips with @tags', E'Different lens than the 6 socials: clips that make Rob look his best to **his** audience and the audiences of people he credits. Pre-record consent for collab posting (add to the booking email if not already in flow).\n\n**Collab A — "Live your life backward" · PRIMARY**\n• Timestamp: ~01:09:00 → ~01:10:00 (~55 sec)\n• On-screen text: "LIVE YOUR LIFE BACKWARD."\n• Caption: Rob Morrow on reading the signs along the path.\n• Platforms: Instagram Reels (collab **@robmorrow**), X\n• Tags: collab @robmorrow. No additional essential tags — this is Rob''s line.\n• Why it flatters Rob: philosophical, articulate, generative. Elder-artist energy.\n\n**Collab B — The Noah Wyle mantra**\n• Timestamp: ~01:15:00 → ~01:15:35 (~35 sec)\n• On-screen text: "THE MANTRA I SAY EVERY DAY."\n• Caption: Rob Morrow on the line Noah Wyle gave him that he repeats daily.\n• Platforms: Instagram (collab **@robmorrow** + tag **@noahwyle**), X\n• Tags: collab @robmorrow + @noahwyle for additional reach into a much larger audience.\n• Why it flatters Rob: generous (credits Noah Wyle), aspirational, deeply quotable. *"Place me in the company of first-class artists with good hearts and good minds doing great work."*\n\n**Collab C — "Drugs keep you from the thing you''re chasing"**\n• Timestamp: ~01:12:25 → ~01:12:44 (~19 sec)\n• On-screen text (paid-reuse safe overlay): "WHAT YOU''RE CHASING IS WHY YOU CAN''T REACH IT."\n• Caption: Rob Morrow with one of the cleanest reframes you''ll hear all year.\n• Platforms: all\n• Tags: collab @robmorrow.\n• Why it flatters Rob: genuine aphorism. Makes him look wise and precise. Universally shareable.\n\nLogistics: send the three finished clip files + a one-line note ("Made these for you — share whichever speak to you, no obligation"). Log acceptance in the tracker.', 170),
  ('Social & Clips', 'Send collab clips to collab partners', E'Send Collab B (Noah Wyle mantra) to **@noahwyle**''s team / channel for boost potential — the Noah Wyle audience is materially larger than Rob''s solo reach.\n\nAlso surface the *Northern Disclosure* listener overlap + Janine Turner''s audience — Collab A (Live Your Life Backward) is the natural send to **@northerndisclosure** / **@janineturner** for reposts.', 180),

  -- Launch Day -----------------------------------------------------------
  ('Launch Day', 'Confirm premiere goes live', 'Watch the premiere start. Confirm the watch page is live and the video is playing.', 190),
  ('Launch Day', 'Post + pin the 3 seeded comments (within ~30 min)', E'Three verbatim comments to copy-paste. Tyler pins **Seed 1** (channel-owner auto-pin); Seeds 2-3 go to two different friends/team posting staggered 60-90 min apart. Reply-active first 24 hours.\n\n**Seed 1 — Self-identification · PIN (Tyler''s account)**\n\n> If you grew up on Northern Exposure and just learned Rob Morrow has quietly been in recovery — this one''s going to hit.\n\nWhy: names a subgroup (Northern Exposure viewers, 45-65) and pairs it with surprise (the recovery angle). High self-id density.\n\n**Seed 2 — Mild pushback · INVITES DEBATE**\n\n> Rob calling anger an "addiction" is either the most useful reframe I''ve heard or a way to dodge responsibility for it. Genuinely torn — which is it?\n\nWhy: respectful disagreement on a beloved framework. Recovery-framing-defenders rush in; personal-responsibility folks agree it lets people off the hook. Both camps reply.\n\n**Seed 3 — Stat ask · DRIVES REPLY FLOOD**\n\n> Rob says he''s "powerless over marijuana and anger." Who else here quit weed? Drop how long it''s been — nobody ever talks about weed sobriety.\n\nWhy: specific, low-effort stat ask + names an under-discussed niche (weed sobriety / "California sober" reckoning). Highest-volume mechanic of the three.\n\n**Do NOT seed anything that gestures at the Al Franken / James Franco / #MeToo segment.** It''s the single highest-engagement topic in the episode and would dogpile the comments into a culture-war frame.', 200),
  ('Launch Day', 'Launch Google Ads (paired with Ads & Marketing item above)', '15-min ad-group build immediately after premiere ends. Pause the campaign if any 🔴 flag surfaces in the first minutes.', 210),
  ('Launch Day', 'Spot-check first 30 min', 'Watch the comment stream, the playback, and any policy flags or unusual notices.', 220),

  -- Post-Launch ----------------------------------------------------------
  ('Post-Launch', 'Day-1 monitor', 'Comments, retention curve, any YouTube policy flags. Respond / address as needed.', 230),
  ('Post-Launch', 'Day-3 ad spend pacing check', 'Confirm the campaign is pacing as expected. Adjust if the $80/day is over/underspending.', 240),
  ('Post-Launch', 'Mark production sheet shipped', 'Update RobMorrow_ProductionSheet.md status. Add a "Recently shipped" entry on the project command center (status.json recentlyShipped array).', 250)
) as x(role_group, title, instructions_md, sort_order);

commit;
